name: mercurius
description: 'For mercurius.'
publish_to: 'none'
version: 3.0.0+108

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  based_list: ^1.1.3+1
  based_local_first_image: ^1.1.0+1
  based_splash_page: ^1.0.1
  based_split_view: ^1.2.3
  cross_file: ^0.3.4+2
  dio: ^5.8.0+1
  dart_date: ^1.5.3
  dynamic_color: ^1.7.0
  file_picker: ^10.2.0
  flex_color_picker: ^3.7.1
  flutter_displaymode: ^0.6.0
  flutter_hooks: ^0.21.2
  flutter_markdown: ^0.7.7+1
  flutter_quill: ^11.4.2
  flutter_svg: ^2.2.0
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.5.2
  intl: ^0.20.2
  image_picker: ^1.1.2
  image_picker_android: ^0.8.12+24
  image_picker_platform_interface: ^2.10.1
  json_annotation: ^4.9.0
  keframe: ^3.0.0
  loading_animation_widget: ^1.3.0
  material_color_utilities: ^0.11.1
  path: ^1.9.1
  path_provider: ^2.1.5
  package_info_plus: ^8.3.0
  pausable_timer: ^3.1.0+3
  photo_view: ^0.15.0
  pub_semver: ^2.2.0
  qweather_icons: ^1.7.0
  riverpod_annotation: ^2.3.5
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  syncfusion_flutter_charts: ^30.1.41
  url_launcher: ^6.3.2
  unicons: ^3.0.0
  vibration: ^3.1.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  custom_lint: ^0.7.3
  freezed: ^2.5.8
  intl_utils: ^2.8.11
  json_serializable: ^6.9.2
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.1

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Saira
      fonts:
        - asset: assets/fonts/Saira/Saira-Thin.ttf
          weight: 100
        - asset: assets/fonts/Saira/Saira-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Saira/Saira-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Saira/Saira-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Saira/Saira-Light.ttf
          weight: 300
        - asset: assets/fonts/Saira/Saira-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Saira/Saira-Regular.ttf
          weight: 400
        - asset: assets/fonts/Saira/Saira-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Saira/Saira-Medium.ttf
          weight: 500
        - asset: assets/fonts/Saira/Saira-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Saira/Saira-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Saira/Saira-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Saira/Saira-Bold.ttf
          weight: 700
        - asset: assets/fonts/Saira/Saira-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Saira/Saira-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Saira/Saira-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Saira/Saira-Black.ttf
          weight: 900
        - asset: assets/fonts/Saira/Saira-BlackItalic.ttf
          weight: 900
          style: italic
    - family: CascadiaCodePL
      fonts:
        - asset: assets/fonts/CascadiaCodePL/CascadiaCodePL-Regular.otf
        - asset: assets/fonts/CascadiaCodePL/CascadiaCodePL-Bold.otf
          weight: 700
        - asset: assets/fonts/CascadiaCodePL/CascadiaCodePL-Italic.otf
          style: italic
        - asset: assets/fonts/CascadiaCodePL/CascadiaCodePL-BoldItalic.otf
          weight: 700
          style: italic
  assets:
    - assets/icon/

flutter_intl:
  enabled: true
  class_name: L10N
  arb_dir: lib/l10n
  output_dir: lib/l10n
